### ISSUE TITLE
Check out linuxdeployqt -unsupported-bundle-everything

### ISSUE THREAD

**Issue by probonopd** [bdantas/make-portable#1]
Check out [linuxdeployqt](https://github.com/probonopd/linuxdeployqt/)'s `-unsupported-bundle-everything` option.

These scripts are using it:

* https://gitlab.com/scribus/scribus/tree/master/AppImage-package
* https://gitlab.com/inkscape/inkscape/tree/master/packaging/appimage

Note that it's undocumented for a reason - building on the oldest system you want to target means less bloat. Bundling everything should imho be just the last resort if your application doesn't compile on older systems (due to developer laziness).

**Comment by bdantas** [comment]
> Check out [linuxdeployqt](https://github.com/probonopd/linuxdeployqt/)'s `-unsupported-bundle-everything` option.
Good to know. Wish I had known about this option a few months ago--would have saved me a lot of time and pain. (But I learned a lot rolling my own, so it was not a waste.)

> Bundling everything should imho be just the last resort if your application doesn't compile on older systems (due to developer laziness).
I agree that laziness is probably #1 reason to build on newer machine and bundle everything for older systems. However, in some cases (like mine) the target machine is ancient but does its job extremely well. There is no need to "upgrade" it but it is impossible to compile for it. So there are some legitimate uses for something like this ;)
